User.create!([
  {email: "admin@test.com", encrypted_password: "$2a$11$mEpQMYjPyjkXpR3t2lycq.Df1w.8nIHCt6Cz2WtGj4saj6euOibsO", reset_password_token: "c53127c1e2bca94c369d99dbc320269c2d7586d9935617f68d70751ec87d11ee", reset_password_sent_at: "2016-12-18 00:58:02", remember_created_at: nil, sign_in_count: 15, current_sign_in_at: "2016-12-18 09:05:13", last_sign_in_at: "2016-12-18 02:22:30", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Елушев С. Н.", role: "admin", approve: true},
  {email: "test@test.com", encrypted_password: "$2a$11$MZEBsiBY02NHGcmYQW./zOmKb1PNAhijetZZSGyPn1FrJRscOJ/2u", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, name: "Филиппов А.А.", role: "teacher", approve: true},
  {email: "test2@test.com", encrypted_password: "$2a$11$qlpsyMn5FK1QXV9/DdBrueRUbbHX/n8BYpJKDTwXzKk5OKnovvH5S", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-12-18 09:08:09", last_sign_in_at: "2016-12-18 09:08:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Ярушкина Н. Г.", role: "teacher", approve: true}
])
Comment.create!([
  {user_id: 1, news_id: 2, title: "asd", content: "sad", date: "2016-12-18 00:30:48"},
  {user_id: 1, news_id: 2, title: "Алло?", content: "123", date: "2016-12-18 00:35:08"},
  {user_id: 1, news_id: 1, title: "dsf", content: "dsf", date: "2016-12-18 01:22:40"},
  {user_id: 1, news_id: 2, title: "fdg", content: "dfgfd", date: "2016-12-18 09:06:01"}
])
Discipline.create!([
  {name: "Операционные системы", user_id: 2, page: "Содержание"},
  {name: "Операционные системы", user_id: 2, page: "<p>Содержание</p>\r\n<table style=\"width: 712px;\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n</tbody>\r\n</table>"},
  {name: "Операционные системы", user_id: 2, page: "<p>Содержание</p>\r\n<table style=\"width: 712px;\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;sda</td>\r\n<td style=\"width: 90px;\">&nbsp;asd</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n</tbody>\r\n</table>"},
  {name: "Операционные системы", user_id: 2, page: "<p>Содержание</p>\r\n<table style=\"width: 712px;\" border=\"1\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;sda</td>\r\n<td style=\"width: 90px;\">&nbsp;asd</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n</tbody>\r\n</table>"},
  {name: "Операционные системы", user_id: 2, page: "<p>Содержание</p>\r\n<table style=\"width: 712px;\" border=\"1\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 76px;\">Лекции</td>\r\n<td style=\"width: 90px;\">&nbsp;Практики</td>\r\n<td style=\"width: 161px;\">Дополнительно&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 76px;\">&nbsp;</td>\r\n<td style=\"width: 90px;\">&nbsp;</td>\r\n<td style=\"width: 161px;\">&nbsp;</td>\r\n<td style=\"width: 397px;\">&nbsp;</td>\r\n</tr>\r\n</tbody>\r\n</table>"}
])
News.create!([
  {user_id: 1, content: "<p>Ололо&nbsp;<a title=\"ыфв\" href=\"../uploads/1/NewFile.txt\">ыфв</a></p>", date: "2016-12-17 23:52:26", title: "Название"},
  {user_id: 1, content: "<p><strong>sssssssss</strong></p>\r\n<p><a href=\"../uploads/1/check_host.zip.html\">asdsa</a></p>", date: "2016-12-17 22:28:00", title: "asdasd"},
  {user_id: 1, content: "<p><a href=\"../uploads/1/check_host.zip.html\">khgjjh</a>&nbsp;Ололол</p>", date: "2016-12-17 22:49:30", title: "Новость!"}
])
